### ISSUE TITLE
Instructions for long hammock?

### ISSUE THREAD

**Issue by wammies** [HummingbirdHammocks/ultralight-hammocks#2]
Are there instructions for the long hammock somewhere? If not, would it be possible to add some? Thanks!

**Comment by loidolt** [comment]
Thanks for checking out our designs!

Use and care instructions can be found here:
https://help.hummingbirdhammocks.com/support/solutions/articles/17000079196-hammock-manual

We don't currently have plans to release sewing/assembly instructions but if we change our mind they would be added to this repo.
